version: "3"

services:
  db:
    container_name: subsquid_db
    image: postgres:12
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

